bootstrap: true
ccp_alpha: 0.0
class_weight:
criterion: gini
max_depth:
max_features: sqrt
max_leaf_nodes:
max_samples:
min_impurity_decrease: 0.0
min_samples_leaf: 1
min_samples_split: 2
min_weight_fraction_leaf: 0.0
n_estimators: 100
n_jobs:
oob_score: false
random_state:
verbose: 0
warm_start: false
